
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.$f||(g.$f=0);g.$f++;
(function(a){function b(n,r,t){var u=new XMLHttpRequest;u.open("GET",n,!0);u.responseType="arraybuffer";u.onprogress=function(w){var y=r;w.total&&(y=w.total);if(w.loaded){u.qf?g.yf[n].loaded=w.loaded:(u.qf=!0,g.yf||(g.yf={}),g.yf[n]={loaded:w.loaded,total:y});var B=y=w=0,D;for(D in g.yf){var I=g.yf[D];w+=I.total;y+=I.loaded;B++}w=Math.ceil(w*g.$f/B);g.setStatus&&g.setStatus("Downloading data... ("+y+"/"+w+")")}else!g.yf&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
n);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)t(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,y,B){this.start=w;this.end=y;this.audio=B}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.Qg=w;w=a.files;for(var y=
0;y<w.length;++y)n.prototype.qf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);n.prototype={qf:{},open:function(w,y){this.name=y;this.qf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.cg(this.Qg.subarray(this.start,this.end))},cg:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.qf[this.name]=null}};for(var t=a.files,u=0;u<t.length;++u)(new n(t[u].start,
t[u].end,t[u].audio)).open("GET",t[u].filename);g.addRunDependency("datafile_build/web/index.data");g.vg||(g.vg={});g.vg["build/web/index.data"]={ih:!1};m?(r(m),m=null):k=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,m=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;m||b(e,f,function(n){k?(k(n),k=null):m=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/assets/atlas.dat",
start:0,end:53,audio:0},{filename:"/assets/atlas.png",start:53,end:1025,audio:0}],remote_package_size:1025,package_uuid:"a95fa237-c5dd-4485-9d65-37c959eed0d1"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;
var l="",ka,la,ma,na,oa;
if(ia)l=ha?require("path").dirname(l)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&p("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":x=[b>>>0,(z=b,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[a>>2]=x[0];v[a+4>>2]=x[1];break;case "float":A[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var xa,ya=!1,za;
function assert(a,b){a||p("Assertion failed: "+b)}function Aa(a){var b=Ba(a.length);a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?Da(C,a,b):""}
function F(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ga(a){var b=Ea(a)+1,c=Ha(b);F(a,q,c,b);return c}var Ia,q,C,va,Ja,v,G,A,wa;
function Ka(){var a=xa.buffer;Ia=a;g.HEAP8=q=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=Ja=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=A=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var H,La=[],Ma=[],Na=[],Oa=[];function Pa(){var a=g.preRun.shift();La.unshift(a)}var Qa=0,Ra=null,Sa=null;function Ta(){Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa)}
function Ua(){Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function p(a){if(g.onAbort)g.onAbort(a);h(a);ya=!0;za=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Va(){return J.startsWith("data:application/octet-stream;base64,")}var J="index.wasm";if(!Va()){var Wa=J;J=g.locateFile?g.locateFile(Wa,l):l+Wa}
function Xa(){var a=J;try{if(a==J&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Ya(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Xa()});if(la)return new Promise(function(a,b){la(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Xa()})}
var z,x,ab={21992:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},22129:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},22353:function(a){var b=g.SDL2;if(a){void 0!==b.capture.Cf&&clearTimeout(b.capture.Cf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.pf&&(b.capture.pf.onaudioprocess=function(){},b.capture.pf.disconnect(),b.capture.pf=void 0);void 0!==b.capture.Nf&&(b.capture.Nf.disconnect(),b.capture.Nf=void 0);void 0!==b.capture.Tf&&(b.capture.Tf=void 0);b.capture=void 0}else void 0!=b.audio.pf&&(b.audio.pf.disconnect(),b.audio.pf=void 0),b.audio=void 0;void 0!==b.lf&&void 0===b.audio&&void 0===b.capture&&(b.lf.close(),b.lf=void 0)},23525:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.lf||("undefined"!==typeof AudioContext?b.lf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.lf=new webkitAudioContext),b.lf&&Za(b.lf));return void 0===b.lf?-1:0},24018:function(){return g.SDL2.lf.sampleRate},24086:function(a,b,c,d){function e(){}function f(m){void 0!==k.capture.Cf&&(clearTimeout(k.capture.Cf),k.capture.Cf=void 0);k.capture.Nf=k.lf.createMediaStreamSource(m);k.capture.pf=k.lf.createScriptProcessor(b,a,1);k.capture.pf.onaudioprocess=function(n){void 0!==
k&&void 0!==k.capture&&(n.outputBuffer.getChannelData(0).fill(0),k.capture.Wf=n.inputBuffer,$a(c,[d]))};k.capture.Nf.connect(k.capture.pf);k.capture.pf.connect(k.lf.destination);k.capture.stream=m}var k=g.SDL2;k.capture.Tf=k.lf.createBuffer(a,b,k.lf.sampleRate);k.capture.Tf.getChannelData(0).fill(0);k.capture.Cf=setTimeout(function(){k.capture.Wf=k.capture.Tf;$a(c,[d])},b/k.lf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},25738:function(a,b,c,d){var e=g.SDL2;e.audio.pf=e.lf.createScriptProcessor(b,0,a);e.audio.pf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.lg=f.outputBuffer,$a(c,[d]))};e.audio.pf.connect(e.lf.destination)},26148:function(a,b){for(var c=g.SDL2,d=c.audio.lg.numberOfChannels,e=0;e<d;++e){var f=c.audio.lg.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=A[a+(k*d+e<<2)>>2]}},26628:function(a,b){for(var c=g.SDL2,d=c.capture.Wf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Wf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)ua(a+4*k,f[k],"float");else for(k=0;k<b;++k)ua(a+4*(k*d+e),f[k],"float")}}};function bb(a,b,c){a.addEventListener(b,c,{once:!0})}
function Za(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&bb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function cb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Kg;"number"===typeof c?void 0===b.Ef?H.get(c)():H.get(c)(b.Ef):c(void 0===b.Ef?null:b.Ef)}}}
function $a(a,b){if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else H.get(a).apply(null,b)}function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Af:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Af.flush(a.tty)},flush:function(a){a.tty.Af.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Af.pg)throw new K(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Af.pg(a.tty)}catch(m){throw new K(29);}if(void 0===k&&0===e)throw new K(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Af.eg)throw new K(60);
try{for(var e=0;e<d;e++)a.tty.Af.eg(a.tty,b[c+e])}catch(f){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},pb={pg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.qf?Buffer.qf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},eg:function(a,b){null===b||10===b?(qa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Da(a.output,0)),a.output=[])}},qb={eg:function(a,b){null===b||10===b?(h(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Da(a.output,0)),a.output=[])}},L={uf:null,vf:function(){return L.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.uf||(L.uf={dir:{node:{tf:L.hf.tf,rf:L.hf.rf,lookup:L.hf.lookup,Of:L.hf.Of,rename:L.hf.rename,unlink:L.hf.unlink,rmdir:L.hf.rmdir,readdir:L.hf.readdir,symlink:L.hf.symlink},stream:{wf:L.jf.wf}},file:{node:{tf:L.hf.tf,rf:L.hf.rf},stream:{wf:L.jf.wf,read:L.jf.read,write:L.jf.write,hg:L.jf.hg,Pf:L.jf.Pf,Rf:L.jf.Rf}},link:{node:{tf:L.hf.tf,rf:L.hf.rf,readlink:L.hf.readlink},stream:{}},kg:{node:{tf:L.hf.tf,
rf:L.hf.rf},stream:rb}});c=sb(a,b,c,d);M(c.mode)?(c.hf=L.uf.dir.node,c.jf=L.uf.dir.stream,c.gf={}):32768===(c.mode&61440)?(c.hf=L.uf.file.node,c.jf=L.uf.file.stream,c.kf=0,c.gf=null):40960===(c.mode&61440)?(c.hf=L.uf.link.node,c.jf=L.uf.link.stream):8192===(c.mode&61440)&&(c.hf=L.uf.kg.node,c.jf=L.uf.kg.stream);c.timestamp=Date.now();a&&(a.gf[b]=c,a.timestamp=c.timestamp);return c},jh:function(a){return a.gf?a.gf.subarray?a.gf.subarray(0,a.kf):new Uint8Array(a.gf):new Uint8Array(0)},mg:function(a,
b){var c=a.gf?a.gf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.gf,a.gf=new Uint8Array(b),0<a.kf&&a.gf.set(c.subarray(0,a.kf),0))},Xg:function(a,b){if(a.kf!=b)if(0==b)a.gf=null,a.kf=0;else{var c=a.gf;a.gf=new Uint8Array(b);c&&a.gf.set(c.subarray(0,Math.min(b,a.kf)));a.kf=b}},hf:{tf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.kf:
40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Gg=4096;b.blocks=Math.ceil(b.size/b.Gg);return b},rf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.Xg(a,b.size)},lookup:function(){throw tb[44];},Of:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(M(a.mode)){try{var d=ub(b,c)}catch(f){}if(d)for(var e in d.gf)throw new K(55);
}delete a.parent.gf[a.name];a.parent.timestamp=Date.now();a.name=c;b.gf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.gf[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ub(a,b),d;for(d in c.gf)throw new K(55);delete a.gf[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.gf)a.gf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(28);
return a.link}},jf:{read:function(a,b,c,d,e){var f=a.node.gf;if(e>=a.node.kf)return 0;a=Math.min(a.node.kf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.gf||a.gf.subarray)){if(f)return a.gf=b.subarray(c,c+d),a.kf=d;if(0===a.kf&&0===e)return a.gf=b.slice(c,c+d),a.kf=d;if(e+d<=a.kf)return a.gf.set(b.subarray(c,c+d),e),d}L.mg(a,e+
d);if(a.gf.subarray&&b.subarray)a.gf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.gf[e+f]=b[c+f];a.kf=Math.max(a.kf,e+d);return d},wf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kf);if(0>b)throw new K(28);return b},hg:function(a,b,c){L.mg(a.node,b+c);a.node.kf=Math.max(a.node.kf,b+c)},Pf:function(a,b,c,d,e,f){if(0!==b)throw new K(28);if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.gf;if(f&2||a.buffer!==Ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ba(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new K(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{Vg:c,Vf:d}},Rf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);if(e&2)return 0;L.jf.write(a,b,0,d,c,!1);return 0}}},vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,Bb={},K=null,tb={};
function Cb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ng:!0,fg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.fg)throw new K(32);a=db(a.split("/").filter(function(k){return!!k}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ub(e,a[d]);c=fb(c+"/"+a[d]);e.Bf&&(!f||f&&b.ng)&&(e=e.Bf.root);if(!f||b.Hf)for(f=0;40960===(e.mode&61440);)if(e=Db(c),c=jb(gb(c),e),e=Cb(c,{fg:b.fg}).node,40<f++)throw new K(32);}return{path:c,node:e}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.vf.tg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function ub(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.hf.lookup?0:2)throw new K(c,a);for(c=zb[Fb(a.id,b)];c;c=c.zf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.hf.lookup(a,b)}
function sb(a,b,c,d){a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.zf=zb[b];return zb[b]=a}function M(a){return 16384===(a&61440)}var Ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return ub(a,b),20}catch(c){}return Gb(a,"wx")}
function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!xb[a])return a;throw new K(33);}function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={});var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return xb[b]=a}var rb={open:function(a){a.jf=wb[a.node.rdev].jf;a.jf.open&&a.jf.open(a)},wf:function(){throw new K(70);}};function mb(a,b){wb[a]={jf:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&vb)throw new K(10);if(!c&&!d){var e=Cb(b,{ng:!1});b=e.path;e=e.node;if(e.Bf)throw new K(10);if(!M(e.mode))throw new K(54);}b={type:a,qh:{},tg:b,Tg:[]};a=a.vf(b);a.vf=b;b.root=a;c?vb=a:e&&(e.Bf=b,e.vf&&e.vf.Tg.push(b))}function Pb(a,b,c){var d=Cb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new K(28);var e=Kb(d,a);if(e)throw new K(e);if(!d.hf.Of)throw new K(63);return d.hf.Of(d,a,b,c)}function Qb(a){return Pb(a,16895,0)}
function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Sb(a,b){if(!jb(a))throw new K(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new K(44);b=hb(b);var d=Kb(c,b);if(d)throw new K(d);if(!c.hf.symlink)throw new K(63);c.hf.symlink(c,b,a)}
function Tb(a){var b=Cb(a,{parent:!0}).node,c=hb(a),d=ub(b,c);a:{try{var e=ub(b,c)}catch(k){e=k.mf;break a}var f=Gb(b,"wx");e=f?f:M(e.mode)?31:0}if(e)throw new K(e);if(!b.hf.unlink)throw new K(63);if(d.Bf)throw new K(10);try{Bb.willDeletePath&&Bb.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.hf.unlink(b,c);b=Fb(d.parent.id,d.name);if(zb[b]===d)zb[b]=d.zf;else for(b=zb[b];b;){if(b.zf===d){b.zf=d.zf;break}b=b.zf}try{if(Bb.onDeletePath)Bb.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Db(a){a=Cb(a).node;if(!a)throw new K(44);if(!a.hf.readlink)throw new K(28);return jb(Eb(a.parent),a.hf.readlink(a))}function Ub(a,b){a="string"===typeof a?Cb(a,{Hf:!0}).node:a;if(!a.hf.rf)throw new K(63);a.hf.rf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Vb(a,b,c,d){if(""===a)throw new K(44);if("string"===typeof b){var e=Ib[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=fb(a);try{f=Cb(a,{Hf:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new K(20);}else f=Pb(a,c,0),e=!0;if(!f)throw new K(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!M(f.mode))throw new K(54);if(!e&&(c=f?40960===(f.mode&61440)?32:M(f.mode)&&
("r"!==Jb(b)||b&512)?31:Gb(f,Jb(b)):44))throw new K(c);if(b&512){c=f;c="string"===typeof c?Cb(c,{Hf:!0}).node:c;if(!c.hf.rf)throw new K(63);if(M(c.mode))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(e=Gb(c,"w"))throw new K(e);c.hf.rf(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Mb({node:f,path:Eb(f),flags:b,seekable:!0,position:0,jf:f.jf,Zg:[],error:!1},d);d.jf.open&&d.jf.open(d);!g.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,h("FS.trackingDelegate error on read file: "+a)));
try{Bb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Bb.onOpenFile(a,f))}catch(k){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Xb(a){if(null===a.fd)throw new K(8);a.bg&&(a.bg=null);try{a.jf.close&&a.jf.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null}function Yb(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.jf.wf)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.jf.wf(a,b,c);a.Zg=[]}
function Zb(a,b,c,d,e,f){if(0>d||0>e)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(M(a.node.mode))throw new K(31);if(!a.jf.write)throw new K(28);a.seekable&&a.flags&1024&&Yb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new K(70);b=a.jf.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Bb.onWriteToFile)Bb.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function $b(){K||(K=function(a,b){this.node=b;this.Yg=function(c){this.mf=c};this.Yg(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(function(a){tb[a]=new K(a);tb[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function cc(a,b){a="string"===typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fb(a+"/"+c);try{Qb(d)}catch(e){}a=d}}return d}
function dc(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);c=bc(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}function ec(a,b,c,d,e,f){a=b?fb(("string"===typeof a?a:Eb(a))+"/"+b):a;d=bc(d,e);e=Pb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Ub(e,d|146);a=Vb(e,577);Zb(a,c,0,c.length,0,f);Xb(a);Ub(e,d)}return e}
function fc(a,b,c,d){a=fb(("string"===typeof a?a:Eb(a))+"/"+b);b=bc(!!c,!!d);fc.rg||(fc.rg=64);var e=fc.rg++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,k,m,n){for(var r=0,t=0;t<n;t++){try{var u=c()}catch(w){throw new K(29);}if(void 0===u&&0===r)throw new K(6);if(null===u||void 0===u)break;r++;k[m+t]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,k,m,n){for(var r=0;r<n;r++)try{d(k[m+r])}catch(t){throw new K(29);}n&&
(f.node.timestamp=Date.now());return r}});return Rb(a,b,e)}function hc(a){if(!(a.Og||a.Pg||a.link||a.gf)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.gf=ob(ka(a.url),!0),a.kf=a.gf.length}catch(b){throw new K(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ic(a,b,c,d,e){function f(){this.dg=!1;this.qf=[]}f.prototype.get=function(t){if(!(t>this.length-1||0>t)){var u=t%this.chunkSize;return this.qg(t/this.chunkSize|0)[u]}};f.prototype.cg=function(t){this.qg=t};f.prototype.ig=function(){var t=new XMLHttpRequest;t.open("HEAD",c,!1);t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);var u=Number(t.getResponseHeader("Content-length")),w,y=(w=t.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;t=(w=t.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=u);var D=this;D.cg(function(I){var eb=I*B,Fa=(I+1)*B-1;Fa=Math.min(Fa,u-1);if("undefined"===typeof D.qf[I]){var oe=D.qf;if(eb>Fa)throw Error("invalid range ("+eb+", "+Fa+") or no bytes requested!");if(Fa>u-1)throw Error("only "+u+" bytes available! programmer error!");var S=new XMLHttpRequest;S.open("GET",c,!1);u!==B&&S.setRequestHeader("Range","bytes="+eb+"-"+Fa);"undefined"!=typeof Uint8Array&&(S.responseType=
"arraybuffer");S.overrideMimeType&&S.overrideMimeType("text/plain; charset=x-user-defined");S.send(null);if(!(200<=S.status&&300>S.status||304===S.status))throw Error("Couldn't load "+c+". Status: "+S.status);eb=void 0!==S.response?new Uint8Array(S.response||[]):ob(S.responseText||"",!0);oe[I]=eb}if("undefined"===typeof D.qf[I])throw Error("doXHR failed!");return D.qf[I]});if(t||!u)B=u=1,B=u=this.qg(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Fg=
u;this.Eg=B;this.dg=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.dg||this.ig();return this.Fg}},chunkSize:{get:function(){this.dg||this.ig();return this.Eg}}});var m=void 0}else m=c,k=void 0;var n=dc(a,b,d,e);k?n.gf=k:m&&(n.gf=null,n.url=m);Object.defineProperties(n,{kf:{get:function(){return this.gf.length}}});
var r={};Object.keys(n.jf).forEach(function(t){var u=n.jf[t];r[t]=function(){hc(n);return u.apply(null,arguments)}});r.read=function(t,u,w,y,B){hc(n);t=t.node.gf;if(B>=t.length)return 0;y=Math.min(t.length-B,y);if(t.slice)for(var D=0;D<y;D++)u[w+D]=t[B+D];else for(D=0;D<y;D++)u[w+D]=t.get(B+D);return y};n.jf=r;return n}
function jc(a,b,c,d,e,f,k,m,n,r){function t(y){function B(I){r&&r();m||ec(a,b,I,d,e,n);f&&f();Ua(w)}var D=!1;g.preloadPlugins.forEach(function(I){!D&&I.canHandle(u)&&(I.handle(y,u,B,function(){k&&k();Ua(w)}),D=!0)});D||B(y)}kc();var u=b?jb(fb(a+"/"+b)):a,w="cp "+u;Ta(w);"string"==typeof c?lc(c,function(y){t(y)},k):t(c)}var N={},Nb,Wb,mc={};
function nc(a,b){try{var c=Cb(a,{Hf:!0}).node;if(!c)throw new K(44);if(!c.hf.tf)throw new K(63);var d=c.hf.tf(c)}catch(e){if(e&&e.node&&fb(a)!==fb(Eb(e.node)))return-54;throw e;}v[b>>2]=d.dev;v[b+4>>2]=0;v[b+8>>2]=d.ino;v[b+12>>2]=d.mode;v[b+16>>2]=d.nlink;v[b+20>>2]=d.uid;v[b+24>>2]=d.gid;v[b+28>>2]=d.rdev;v[b+32>>2]=0;x=[d.size>>>0,(z=d.size,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[b+40>>2]=x[0];v[b+44>>2]=x[1];
v[b+48>>2]=4096;v[b+52>>2]=d.blocks;v[b+56>>2]=d.atime.getTime()/1E3|0;v[b+60>>2]=0;v[b+64>>2]=d.mtime.getTime()/1E3|0;v[b+68>>2]=0;v[b+72>>2]=d.ctime.getTime()/1E3|0;v[b+76>>2]=0;x=[d.ino>>>0,(z=d.ino,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[b+80>>2]=x[0];v[b+84>>2]=x[1];return 0}var oc=void 0;function pc(){oc+=4;return v[oc-4>>2]}function qc(a){a=xb[a];if(!a)throw new K(8);return a}var rc;
ia?rc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?rc=dateNow:rc=function(){return performance.now()};var sc=[];function tc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function uc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function vc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var wc=1,xc=[],O=[],yc=[],zc=[],Ac=[],P=[],Bc=[],Cc=[],Q=[],R=[],Dc=[],Ec=[],Fc={},Gc={},Hc=4;function T(a){Ic||(Ic=a)}function Jc(a){for(var b=wc++,c=a.length;c<b;c++)a[c]=null;return b}function Kc(a,b){a.og||(a.og=a.getContext,a.getContext=function(d,e){e=a.og(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.sg?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Lc(c,b):0}
function Lc(a,b){var c=Jc(Cc),d={kh:c,attributes:b,version:b.sg,Uf:a};a.canvas&&(a.canvas.bh=d);Cc[c]=d;("undefined"===typeof b.Jg||b.Jg)&&Mc(d);return c}
function Mc(a){a||(a=U);if(!a.Mg){a.Mg=!0;var b=a.Uf;tc(b);uc(b);vc(b);b.gh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.lh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.nf=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.nf)b.nf=b.getExtension("EXT_disjoint_timer_query");b.oh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Nc={},Ic,U,Oc=[];function Pc(a,b,c,d){for(var e=0;e<a;e++){var f=V[c](),k=f&&Jc(d);f?(f.name=k,d[k]=f):T(1282);v[b+4*e>>2]=k}}function Qc(a,b,c,d,e,f,k,m){b=O[b];if(a=V[a](b,c))d=m&&F(a.name,C,m,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),k&&(v[k>>2]=a.type)}function Rc(a,b){G[a>>2]=b;G[a+4>>2]=(b-G[a>>2])/4294967296}
function Sc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){T(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Rc(b,d);break;case 0:v[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else T(1281)}
function Tc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T(1280);return}break;default:T(1280);return}switch(d){case 1:Rc(c,a);break;case 0:v[c>>2]=a;break;case 2:A[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T(1281)}
function Uc(a){var b=Ea(a)+1,c=Ba(b);F(a,C,c,b);return c}function Vc(a,b,c,d){if(c)if(a=O[a],a=V.getUniform(a,a.Df[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else T(1281)}
function Wc(a,b,c,d){if(c)if(a=V.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else T(1281)}function Xc(a){a-=5120;return 0==a?q:1==a?C:2==a?va:4==a?v:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?G:Ja}
function Yc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Zc(a,b,c,d,e){a=Xc(a);var f=Yc(a),k=Hc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}function W(a){var b=V.Ig,c=b.Df[a];0<=c&&(b.Df[a]=c=V.getUniformLocation(b,b.Ag[a]+(0<c?"["+c+"]":"")));return c}var $c=[],ad=[];
function bd(a){if(!ya)try{a()}catch(b){if(!(b instanceof pa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&h("exception thrown: "+[b,b.stack]),b;}}var cd=!1,dd=null,ed=0,fd=null,gd=0,hd=0,id=0,jd=0,kd=[],ld={},md,nd,od,pd=!1,qd=!1,rd=[];
function kc(){function a(){qd=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!sd){sd=!0;try{td=!0}catch(c){td=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}ud="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:td?null:console.log("warning: no BlobBuilder");
vd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ug||"undefined"!==typeof vd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ug=!0);g.preloadPlugins.push({canHandle:function(c){return!g.ug&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(td)try{k=new Blob([c],{type:wd(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:wd(d)}))}catch(r){ra("Blob constructor present but fails: "+
r+"; falling back to blob builder")}k||(k=new ud,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=vd.createObjectURL(k),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=r;vd.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.ph&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function k(u){n||(n=!0,g.preloadedAudios[d]=u,e&&e(c))}function m(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(td){try{var r=new Blob([c],{type:wd(d)})}catch(u){return m()}r=vd.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",function(){k(t)},!1);t.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,y=0,
B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var D=w>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+u;k(t)}};t.src=r;xd(function(){k(t)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!qd&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function yd(a,b,c,d){if(b&&g.xf&&a==g.canvas)return g.xf;var e;if(b){var f={antialias:!1,alpha:!1,sg:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!==typeof Nc&&(e=Kc(a,f)))var m=Cc[e].Uf}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.xf=m,b&&(U=Cc[e],g.xf=V=U&&U.Uf),g.rh=b,rd.forEach(function(n){n()}),kc());return m}
var zd=!1,Ad=void 0,Bd=void 0;
function Cd(a,b){function c(){pd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Dd,Ad&&d.requestPointerLock(),pd=!0,Bd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Ed(g.canvas),Fd()):Ed(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Bd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Ed(g.canvas),Fd()):Ed(d));if(g.onFullScreen)g.onFullScreen(pd);if(g.onFullscreen)g.onFullscreen(pd)}Ad=a;Bd=b;"undefined"===typeof Ad&&(Ad=!0);"undefined"===typeof Bd&&(Bd=!1);var d=g.canvas;zd||(zd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Dd(){if(!pd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Gd=0;function Hd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Gd)Gd=b+1E3/60;else for(;b+2>=Gd;)Gd+=1E3/60;setTimeout(a,Math.max(Gd-b,0))}}function xd(a){setTimeout(function(){bd(a)},1E4)}
function wd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Id=0,Jd=0,Kd=0,Ld=0;
function Md(a){if(qd)"mousemove"!=a.type&&"mozMovementX"in a?Kd=Ld=0:(Kd=a.movementX||a.mozMovementX||a.webkitMovementX||0,Ld=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Id=SDL.mh+Kd,Jd=SDL.nh+Ld):(Id+=Kd,Jd+=Ld);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Kd=e-Id,Ld=a-Jd,Id=e,Jd=a)}}function lc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ua(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ta(d)}var Nd=[];function Fd(){var a=g.canvas;Nd.forEach(function(b){b(a.width,a.height)})}function Od(a,b,c){Ed(g.canvas,a,b);c||Fd()}
function Ed(a,b,c){b&&c?(a.ah=b,a.Lg=c):(b=a.ah,c=a.Lg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Bd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var sd,td,ud,vd;
function Pd(a,b){hd=a;id=b;if(fd)if(cd||(cd=!0),0==a)dd=function(){var d=Math.max(0,nd+b-rc())|0;setTimeout(od,d)};else if(1==a)dd=function(){Hd(od)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}dd=function(){setImmediate(od)}}}
function Qd(a,b,c,d,e){function f(){if(k<ed){if(!noExitRuntime)try{Rd(za)}catch(m){if(!(m instanceof pa))throw m;}return!1}return!0}assert(!fd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");fd=a;gd=d;var k=ed;cd=!1;od=function(){if(!ya)if(0<kd.length){var m=Date.now(),n=kd.shift();n.Kg(n.Ef);if(md){var r=md,t=0==r%1?r-1:Math.floor(r);md=n.fh?t:(8*r+(t+.5))/
9}console.log('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");g.setStatus&&(m=g.statusMessage||"Please wait...",n=md,r=ld.hh,n?n<r?g.setStatus(m+" ("+(r-n)+"/"+r+")"):g.setStatus(m):g.setStatus(""));f()&&setTimeout(od,0)}else f()&&(jd=jd+1|0,1==hd&&1<id&&0!=jd%id?dd():(0==hd&&(nd=rc()),ya||g.preMainLoop&&!1===g.preMainLoop()||(bd(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Wg&&SDL.audio.Wg(),dd())))};e||(b&&0<b?Pd(0,1E3/b):Pd(1,1),dd());if(c)throw"unwind";
}var Sd={};function Td(){if(!Ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Sd)a[b]=Sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ud=c}return Ud}var Ud;
function Vd(a,b,c,d){this.id=a;this.y=this.x=0;this.ag=!1;this.zg=this.yg=0;this.width=b;this.height=c;this.xg=b;this.wg=c;this.title=d;this.attributes=Wd;this.buttons=0;this.keys=[];this.Yf=[];this.jg=this.Jf=this.Zf=this.Sf=this.Ff=this.Gf=this.Qf=this.If=this.Cg=this.Bg=this.Dg=this.title=null}function Xd(a){return 0>=a||!X?null:X[a-1]}
var Yd=null,Y=null,X=null,Wd=null,Zd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function $d(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function ae(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function be(a){Y&&Y.jg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||H.get(Y.jg)(Y.id,a))}
function ce(a,b){if(Y){var c=$d(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Yf[a]=b;Y.Jf&&(d&&(b=2),H.get(Y.Jf)(Y.id,c,a,b,ae()))}}}function de(){ee()}function fe(){ee()}function ge(a){ce(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function he(a){ce(a.keyCode,0)}function ie(){if(Y)for(var a=0;a<Y.Yf.length;++a)Y.Yf[a]&&ce(a,0)}function je(a){Y&&(Md(a),a.target==g.canvas&&Y.Gf&&H.get(Y.Gf)(Y.id,Id,Jd))}function ke(a){Y&&a.target==g.canvas&&Y.Ff&&H.get(Y.Ff)(Y.id,1)}
function le(a){Y&&a.target==g.canvas&&Y.Ff&&H.get(Y.Ff)(Y.id,0)}function me(a,b){if(Y&&(Md(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Qf&&H.get(Y.Qf)(Y.id,c,b,ae())}}function ne(a){Y&&me(a,1)}function pe(a){Y&&me(a,0)}
function qe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Sf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;H.get(Y.Sf)(Y.id,b,c);a.preventDefault()}}var re={},se=null,te=null;
function ee(){if(jd!==te||!jd){se=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;te=jd;for(var a=0;a<se.length;++a){var b=se[a];if(b){re[a]||(console.log("glfw joystick connected:",a),re[a]={id:Aa(ob(b.id)),eh:b.buttons.length,dh:b.axes.length,buttons:Aa(Array(b.buttons.length)),axes:Aa(Array(4*b.axes.length))});for(var c=re[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else re[a]&&(console.log("glfw joystick disconnected",a),ue(re[a].id),ue(re[a].buttons),ue(re[a].axes),delete re[a])}}}
function ve(a){function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=function(u){if(2!=r.readyState)++f,console.log("failed to read dropped file: "+m.name+": "+r.error);else{var w=new Uint8Array(u.target.result);var y=y||{};y.flags=y.flags||577;u=Vb(n,y.flags,y.mode);if("string"===typeof w){var B=new Uint8Array(Ea(w)+1);w=F(w,B,0,B.length);Zb(u,B,0,w,void 0,y.Hg)}else if(ArrayBuffer.isView(w))Zb(u,w,0,w.byteLength,void 0,y.Hg);else throw Error("Unsupported data type");
Xb(u);if(++f===e){H.get(Y.Zf)(Y.id,e,c);for(y=0;y<d.length;++y)ue(d[y]);ue(c)}}};r.readAsArrayBuffer(m);var t=Aa(ob(n));d.push(t);ua(c+4*k,t,"i8*")}if(Y&&Y.Zf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Aa(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;cc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function we(a){if(Y&&Y.Zf)return a.preventDefault(),!1}
function Hb(a,b,c,d){a||(a=this);this.parent=a;this.vf=a.vf;this.Bf=null;this.id=yb++;this.name=b;this.mode=c;this.hf={};this.jf={};this.rdev=d}Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Pg:{get:function(){return M(this.mode)}},Og:{get:function(){return 8192===(this.mode&61440)}}});$b();zb=Array(4096);
Ob(L,"/");Qb("/tmp");Qb("/home");Qb("/home/web_user");(function(){Qb("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Rb("/dev/null",259);lb(1280,pb);lb(1536,qb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=ib();fc("/dev","random",a);fc("/dev","urandom",a);Qb("/dev/shm");Qb("/dev/shm/tmp")})();
(function(){Qb("/proc");var a=Qb("/proc/self");Qb("/proc/self/fd");Ob({vf:function(){var b=sb(a,"fd",16895,73);b.hf={lookup:function(c,d){var e=xb[+d];if(!e)throw new K(8);c={parent:null,vf:{tg:"fake"},hf:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=fc;g.FS_unlink=Tb;for(var V,Z=0;32>Z;++Z)Oc.push(Array(Z));var xe=new Float32Array(288);
for(Z=0;288>Z;++Z)$c[Z]=xe.subarray(0,Z+1);var ye=new Int32Array(288);for(Z=0;288>Z;++Z)ad[Z]=ye.subarray(0,Z+1);g.requestFullscreen=function(a,b){Cd(a,b)};g.requestAnimationFrame=function(a){Hd(a)};g.setCanvasSize=function(a,b,c){Od(a,b,c)};g.pauseMainLoop=function(){dd=null;ed++};g.resumeMainLoop=function(){ed++;var a=hd,b=id,c=fd;fd=null;Qd(c,0,!1,gd,!0);Pd(a,b);dd()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return yd(a,b,c,d)};function ob(a,b){var c=Array(Ea(a)+1);a=F(a,c,0,c.length);b&&(c.length=a);return c}
var Ce={a:function(a,b,c,d){p("Assertion failed: "+E(a)+", at: "+[b?E(b):"unknown filename",c,d?E(d):"unknown function"])},n:function(a,b,c){oc=c;try{var d=qc(a);switch(b){case 0:var e=pc();return 0>e?-28:Vb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 12:return e=pc(),va[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return v[ze()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof N&&f instanceof K||
p(f),-f.mf}},Sa:function(a,b){try{var c=qc(a);return nc(c.path,b)}catch(d){return"undefined"!==typeof N&&d instanceof K||p(d),-d.mf}},Ua:function(a,b,c){oc=c;try{var d=qc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=pc();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=pc();if(!d.jf.Ng)throw new K(59);return d.jf.Ng(d,b,a);case 21523:return d.tty?0:-59;
case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof N&&f instanceof K||p(f),-f.mf}},Xa:function(a,b,c,d,e,f){try{a:{f<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var m=-28;else{if(0!==(d&32)){var n=Ae(16384,b);if(!n){m=-48;break a}Be(n,0,b);k=!0}else{var r=xb[e];if(!r){m=-8;break a}var t=f;if(0!==(c&2)&&0===(d&2)&&2!==(r.flags&2097155))throw new K(2);if(1===(r.flags&2097155))throw new K(2);if(!r.jf.Pf)throw new K(43);var u=r.jf.Pf(r,a,b,t,c,d);n=u.Vg;
k=u.Vf}mc[n]={Sg:n,Rg:b,Vf:k,fd:e,Ug:c,flags:d,offset:f};m=n}}return m}catch(w){return"undefined"!==typeof N&&w instanceof K||p(w),-w.mf}},Va:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=mc[a];if(d&&b===d.Rg){var e=xb[d.fd];if(e&&d.Ug&2){var f=d.flags,k=d.offset,m=C.slice(a,a+b);e&&e.jf.Rf&&e.jf.Rf(e,m,k,b,f)}mc[a]=null;d.Vf&&ue(d.Sg)}c=0}return c}catch(n){return"undefined"!==typeof N&&n instanceof K||p(n),-n.mf}},o:function(a,b,c){oc=c;try{var d=E(a),e=c?pc():0;return Vb(d,b,e).fd}catch(f){return"undefined"!==
typeof N&&f instanceof K||p(f),-f.mf}},Ra:function(a,b){try{return a=E(a),nc(a,b)}catch(c){return"undefined"!==typeof N&&c instanceof K||p(c),-c.mf}},La:function(){p()},g:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=rc();else return v[ze()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},b:function(a,b,c){sc.length=0;var d;for(c>>=2;d=C[b++];)(d=105>d)&&c&1&&c++,sc.push(d?wa[c++>>1]:v[c]),++c;return ab[a].apply(null,sc)},sa:function(a){V.activeTexture(a)},ra:function(a,b){V.attachShader(O[a],
P[b])},Mc:function(a,b){V.beginQuery(a,Q[b])},Pa:function(a,b){V.nf.beginQueryEXT(a,Q[b])},rc:function(a){V.beginTransformFeedback(a)},qa:function(a,b,c){V.bindAttribLocation(O[a],b,E(c))},oa:function(a,b){35051==a?V.Xf=b:35052==a&&(V.sf=b);V.bindBuffer(a,xc[b])},oc:function(a,b,c){V.bindBufferBase(a,b,xc[c])},pc:function(a,b,c,d,e){V.bindBufferRange(a,b,xc[c],d,e)},na:function(a,b){V.bindFramebuffer(a,yc[b])},ma:function(a,b){V.bindRenderbuffer(a,zc[b])},vb:function(a,b){V.bindSampler(a,R[b])},la:function(a,
b){V.bindTexture(a,Ac[b])},mb:function(a,b){V.bindTransformFeedback(a,Dc[b])},wc:function(a){V.bindVertexArray(Bc[a])},Ba:function(a){V.bindVertexArray(Bc[a])},ka:function(a,b,c,d){V.blendColor(a,b,c,d)},ja:function(a){V.blendEquation(a)},ia:function(a,b){V.blendEquationSeparate(a,b)},ha:function(a,b){V.blendFunc(a,b)},ga:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Ac:function(a,b,c,d,e,f,k,m,n,r){V.blitFramebuffer(a,b,c,d,e,f,k,m,n,r)},fa:function(a,b,c,d){2<=U.version?c?V.bufferData(a,C,d,c,
b):V.bufferData(a,b,d):V.bufferData(a,c?C.subarray(c,c+b):b,d)},da:function(a,b,c,d){2<=U.version?V.bufferSubData(a,b,C,d,c):V.bufferSubData(a,b,C.subarray(d,d+c))},ca:function(a){return V.checkFramebufferStatus(a)},ba:function(a){V.clear(a)},Sb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Tb:function(a,b,c){V.clearBufferfv(a,b,A,c>>2)},Vb:function(a,b,c){V.clearBufferiv(a,b,v,c>>2)},Ub:function(a,b,c){V.clearBufferuiv(a,b,G,c>>2)},aa:function(a,b,c,d){V.clearColor(a,b,c,d)},$:function(a){V.clearDepth(a)},
_:function(a){V.clearStencil(a)},Eb:function(a,b,c,d){return V.clientWaitSync(Ec[a],b,(c>>>0)+4294967296*d)},Z:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},Y:function(a){V.compileShader(P[a])},X:function(a,b,c,d,e,f,k,m){2<=U.version?V.sf?V.compressedTexImage2D(a,b,c,d,e,f,k,m):V.compressedTexImage2D(a,b,c,d,e,f,C,m,k):V.compressedTexImage2D(a,b,c,d,e,f,m?C.subarray(m,m+k):null)},Rc:function(a,b,c,d,e,f,k,m,n){V.sf?V.compressedTexImage3D(a,b,c,d,e,f,k,m,n):V.compressedTexImage3D(a,b,c,d,e,f,k,
C,n,m)},W:function(a,b,c,d,e,f,k,m,n){2<=U.version?V.sf?V.compressedTexSubImage2D(a,b,c,d,e,f,k,m,n):V.compressedTexSubImage2D(a,b,c,d,e,f,k,C,n,m):V.compressedTexSubImage2D(a,b,c,d,e,f,k,n?C.subarray(n,n+m):null)},Qc:function(a,b,c,d,e,f,k,m,n,r,t){V.sf?V.compressedTexSubImage3D(a,b,c,d,e,f,k,m,n,r,t):V.compressedTexSubImage3D(a,b,c,d,e,f,k,m,n,C,t,r)},Qb:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},U:function(a,b,c,d,e,f,k,m){V.copyTexImage2D(a,b,c,d,e,f,k,m)},T:function(a,b,c,d,e,f,k,m){V.copyTexSubImage2D(a,
b,c,d,e,f,k,m)},Sc:function(a,b,c,d,e,f,k,m,n){V.copyTexSubImage3D(a,b,c,d,e,f,k,m,n)},S:function(){var a=Jc(O),b=V.createProgram();b.name=a;b.Mf=b.Kf=b.Lf=0;b.gg=1;O[a]=b;return a},R:function(a){var b=Jc(P);P[b]=V.createShader(a);return b},Q:function(a){V.cullFace(a)},P:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xc[d];e&&(V.deleteBuffer(e),e.name=0,xc[d]=null,d==V.Xf&&(V.Xf=0),d==V.sf&&(V.sf=0))}},O:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=yc[d];e&&(V.deleteFramebuffer(e),
e.name=0,yc[d]=null)}},N:function(a){if(a){var b=O[a];b?(V.deleteProgram(b),b.name=0,O[a]=null):T(1281)}},Oc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(V.deleteQuery(e),Q[d]=null)}},fb:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(V.nf.deleteQueryEXT(e),Q[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zc[d];e&&(V.deleteRenderbuffer(e),e.name=0,zc[d]=null)}},xb:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(V.deleteSampler(e),
e.name=0,R[d]=null)}},L:function(a){if(a){var b=P[a];b?(V.deleteShader(b),P[a]=null):T(1281)}},Fb:function(a){if(a){var b=Ec[a];b?(V.deleteSync(b),b.name=0,Ec[a]=null):T(1281)}},J:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ac[d];e&&(V.deleteTexture(e),e.name=0,Ac[d]=null)}},lb:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Dc[d];e&&(V.deleteTransformFeedback(e),e.name=0,Dc[d]=null)}},vc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];V.deleteVertexArray(Bc[d]);Bc[d]=null}},
za:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];V.deleteVertexArray(Bc[d]);Bc[d]=null}},I:function(a){V.depthFunc(a)},H:function(a){V.depthMask(!!a)},G:function(a,b){V.depthRange(a,b)},F:function(a,b){V.detachShader(O[a],P[b])},E:function(a){V.disable(a)},D:function(a){V.disableVertexAttribArray(a)},C:function(a,b,c){V.drawArrays(a,b,c)},Jb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},va:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},ad:function(a,b,c,d){V.drawArraysInstanced(a,b,
c,d)},bd:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Ya:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Hc:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},Yc:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},wa:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},B:function(a,b,c,d){V.drawElements(a,b,c,d)},Ib:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},ua:function(a,b,c,d,e){V.drawElementsInstanced(a,
b,c,d,e)},Zc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},_c:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},$c:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e,f){V.drawElements(a,d,e,f)},A:function(a){V.enable(a)},y:function(a){V.enableVertexAttribArray(a)},Lc:function(a){V.endQuery(a)},Ia:function(a){V.nf.endQueryEXT(a)},qc:function(){V.endTransformFeedback()},Hb:function(a,b){return(a=V.fenceSync(a,b))?(b=Jc(Ec),a.name=b,Ec[b]=a,b):0},x:function(){V.finish()},
w:function(){V.flush()},v:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,zc[d])},u:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,Ac[d],e)},xc:function(a,b,c,d,e){V.framebufferTextureLayer(a,b,Ac[c],d,e)},t:function(a){V.frontFace(a)},s:function(a,b){Pc(a,b,"createBuffer",xc)},q:function(a,b){Pc(a,b,"createFramebuffer",yc)},Pc:function(a,b){Pc(a,b,"createQuery",Q)},qb:function(a,b){for(var c=0;c<a;c++){var d=V.nf.createQueryEXT();if(!d){for(T(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Jc(Q);d.name=
e;Q[e]=d;v[b+4*c>>2]=e}},p:function(a,b){Pc(a,b,"createRenderbuffer",zc)},yb:function(a,b){Pc(a,b,"createSampler",R)},Ue:function(a,b){Pc(a,b,"createTexture",Ac)},kb:function(a,b){Pc(a,b,"createTransformFeedback",Dc)},uc:function(a,b){Pc(a,b,"createVertexArray",Bc)},ya:function(a,b){Pc(a,b,"createVertexArray",Bc)},r:function(a){V.generateMipmap(a)},Te:function(a,b,c,d,e,f,k){Qc("getActiveAttrib",a,b,c,d,e,f,k)},Se:function(a,b,c,d,e,f,k){Qc("getActiveUniform",a,b,c,d,e,f,k)},Lb:function(a,b,c,d,e){a=
O[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=F(a,C,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},Mb:function(a,b,c,d){if(d)if(a=O[a],35393==c)c=V.getActiveUniformBlockName(a,b),v[d>>2]=c.length+1;else{if(a=V.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)v[d+4*c>>2]=a[c];else v[d>>2]=a}else T(1281)},Ob:function(a,b,c,d,e){if(e)if(0<b&&0==c)T(1281);else{a=O[a];for(var f=[],k=0;k<b;k++)f.push(v[c+4*k>>2]);if(a=V.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)v[e+
4*k>>2]=a[k]}else T(1281)},Re:function(a,b,c,d){a=V.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=P.indexOf(a[b])},Qe:function(a,b){return V.getAttribLocation(O[a],E(b))},Pe:function(a,b){Sc(a,b,4)},zb:function(a,b,c){c?Rc(c,V.getBufferParameter(a,b)):T(1281)},Oe:function(a,b,c){c?v[c>>2]=V.getBufferParameter(a,b):T(1281)},Ne:function(){var a=V.getError()||Ic;Ic=0;return a},Me:function(a,b){Sc(a,b,2)},cc:function(a,b){return V.getFragDataLocation(O[a],E(b))},
Le:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Ab:function(a,b,c){Tc(a,b,c,1)},Cb:function(a,b){Sc(a,b,1)},sc:function(a,b,c){Tc(a,b,c,0)},Ke:function(a,b){Sc(a,b,0)},_a:function(a,b,c,d,e){if(0>d)T(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+b>>2]=a[b]}else T(1281)},gb:function(){T(1282)},Ie:function(a,b,c,d){a=V.getProgramInfoLog(O[a]);null===
a&&(a="(unknown error)");b=0<b&&d?F(a,C,d,b):0;c&&(v[c>>2]=b)},Je:function(a,b,c){if(c)if(a>=wc)T(1281);else if(a=O[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Mf)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Mf=Math.max(a.Mf,V.getActiveUniform(a,b).name.length+1);v[c>>2]=a.Mf}else if(35722==b){if(!a.Kf)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Kf=Math.max(a.Kf,V.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Kf}else if(35381==
b){if(!a.Lf)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Lf=Math.max(a.Lf,V.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Lf}else v[c>>2]=V.getProgramParameter(a,b);else T(1281)},Da:function(a,b,c){if(c){a=Q[a];b=2>U.version?V.nf.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Rc(c,d)}else T(1281)},Fa:function(a,b,c){if(c){a=V.nf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Ca:function(a,b,c){if(c){a=Q[a];b=2>
U.version?V.nf.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Rc(c,d)}else T(1281)},Ic:function(a,b,c){if(c){a=V.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Ea:function(a,b,c){if(c){a=V.nf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Kc:function(a,b,c){c?v[c>>2]=V.getQuery(a,b):T(1281)},Ga:function(a,b,c){c?v[c>>2]=V.nf.getQueryEXT(a,b):T(1281)},He:function(a,b,c){c?v[c>>2]=
V.getRenderbufferParameter(a,b):T(1281)},ob:function(a,b,c){c?A[c>>2]=V.getSamplerParameter(R[a],b):T(1281)},pb:function(a,b,c){c?v[c>>2]=V.getSamplerParameter(R[a],b):T(1281)},Fe:function(a,b,c,d){a=V.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,C,d,b):0;c&&(v[c>>2]=b)},Ee:function(a,b,c,d){a=V.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},De:function(a,b,c,d){if(a=V.getShaderSource(P[a]))b=0<b&&d?F(a,C,d,b):0,c&&(v[c>>2]=b)},Ge:function(a,
b,c){c?35716==b?(a=V.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(P[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=V.getShaderParameter(P[a],b):T(1281)},Ce:function(a){var b=Fc[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Uc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||T(1280);b=b&&Uc(b);break;case 7938:b=V.getParameter(7938);b=2<=U.version?
"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Uc(b);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Uc(b);break;default:T(1280)}Fc[a]=b}return b},Rb:function(a,b){if(2>U.version)return T(1282),0;var c=Gc[a];if(c)return 0>b||b>=c.length?(T(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=
c.map(function(d){return Uc(d)}),c=Gc[a]=c,0>b||b>=c.length?(T(1281),0):c[b];default:return T(1280),0}},Bb:function(a,b,c,d,e){0>c?T(1281):e?(a=V.getSyncParameter(Ec[a],b),null!==a&&(v[e>>2]=a,d&&(v[d>>2]=1))):T(1281)},Be:function(a,b,c){c?A[c>>2]=V.getTexParameter(a,b):T(1281)},ze:function(a,b,c){c?v[c>>2]=V.getTexParameter(a,b):T(1281)},lc:function(a,b,c,d,e,f,k){a=O[a];if(a=V.getTransformFeedbackVarying(a,b))k&&0<c?(c=F(a.name,C,k,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>
2]=a.type)},Nb:function(a,b){return V.getUniformBlockIndex(O[a],E(b))},Pb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))T(1281);else{a=O[a];for(var e=[],f=0;f<b;f++)e.push(E(v[c+4*f>>2]));if(a=V.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else T(1281)},we:function(a,b){function c(y){return"]"==y.slice(-1)&&y.lastIndexOf("[")}b=E(b);a=O[a];var d=a.Df,e=a.$g,f,k=0,m=b,n=c(b);if(!d)for(a.Df=d={},a.Ag={},f=0;f<V.getProgramParameter(a,35718);++f){var r=V.getActiveUniform(a,f);var t=
r.name;r=r.size;var u=c(t);u=0<u?t.slice(0,u):t;var w=a.gg;a.gg+=r;e[u]=[r,w];for(t=0;t<r;++t)d[w]=t,a.Ag[w++]=u}0<n&&(k=parseInt(b.slice(n+1))>>>0,m=b.slice(0,n));return(e=e[m])&&k<e[0]&&(k+=e[1],d[k]=d[k]||V.getUniformLocation(a,b))?k:-1},ye:function(a,b,c){Vc(a,b,c,2)},xe:function(a,b,c){Vc(a,b,c,0)},dc:function(a,b,c){Vc(a,b,c,0)},jc:function(a,b,c){Wc(a,b,c,0)},ic:function(a,b,c){Wc(a,b,c,0)},te:function(a,b,c){c?v[c>>2]=V.getVertexAttribOffset(a,b):T(1281)},ve:function(a,b,c){Wc(a,b,c,2)},ue:function(a,
b,c){Wc(a,b,c,5)},se:function(a,b){V.hint(a,b)},cb:function(a,b,c){for(var d=Oc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];V.invalidateFramebuffer(a,d)},bb:function(a,b,c,d,e,f,k){for(var m=Oc[b],n=0;n<b;n++)m[n]=v[c+4*n>>2];V.invalidateSubFramebuffer(a,m,d,e,f,k)},re:function(a){return(a=xc[a])?V.isBuffer(a):0},qe:function(a){return V.isEnabled(a)},oe:function(a){return(a=yc[a])?V.isFramebuffer(a):0},ne:function(a){return(a=O[a])?V.isProgram(a):0},Nc:function(a){return(a=Q[a])?V.isQuery(a):0},Wa:function(a){return(a=
Q[a])?V.nf.isQueryEXT(a):0},me:function(a){return(a=zc[a])?V.isRenderbuffer(a):0},wb:function(a){return(a=R[a])?V.isSampler(a):0},le:function(a){return(a=P[a])?V.isShader(a):0},Gb:function(a){return V.isSync(Ec[a])},ke:function(a){return(a=Ac[a])?V.isTexture(a):0},jb:function(a){return V.isTransformFeedback(Dc[a])},tc:function(a){return(a=Bc[a])?V.isVertexArray(a):0},xa:function(a){return(a=Bc[a])?V.isVertexArray(a):0},je:function(a){V.lineWidth(a)},ie:function(a){a=O[a];V.linkProgram(a);a.Df=0;a.$g=
{}},ib:function(){V.pauseTransformFeedback()},he:function(a,b){3317==a&&(Hc=b);V.pixelStorei(a,b)},ge:function(a,b){V.polygonOffset(a,b)},eb:function(){T(1280)},db:function(){T(1280)},Ha:function(a,b){V.nf.queryCounterEXT(Q[a],b)},Xc:function(a){V.readBuffer(a)},fe:function(a,b,c,d,e,f,k){if(2<=U.version)if(V.Xf)V.readPixels(a,b,c,d,e,f,k);else{var m=Xc(f);V.readPixels(a,b,c,d,e,f,m,k>>Yc(m))}else(k=Zc(f,e,c,d,k))?V.readPixels(a,b,c,d,e,f,k):T(1280)},de:function(){},ce:function(a,b,c,d){V.renderbufferStorage(a,
b,c,d)},zc:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},hb:function(){V.resumeTransformFeedback()},be:function(a,b){V.sampleCoverage(a,!!b)},sb:function(a,b,c){V.samplerParameterf(R[a],b,c)},rb:function(a,b,c){V.samplerParameterf(R[a],b,A[c>>2])},ub:function(a,b,c){V.samplerParameteri(R[a],b,c)},tb:function(a,b,c){V.samplerParameteri(R[a],b,v[c>>2])},ae:function(a,b,c,d){V.scissor(a,b,c,d)},$d:function(){T(1280)},_d:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?v[d+4*f>>
2]:-1;e+=E(v[c+4*f>>2],0>k?void 0:k)}V.shaderSource(P[a],e)},Zd:function(a,b,c){V.stencilFunc(a,b,c)},Yd:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},Xd:function(a){V.stencilMask(a)},Wd:function(a,b){V.stencilMaskSeparate(a,b)},Ud:function(a,b,c){V.stencilOp(a,b,c)},Td:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Sd:function(a,b,c,d,e,f,k,m,n){if(2<=U.version)if(V.sf)V.texImage2D(a,b,c,d,e,f,k,m,n);else if(n){var r=Xc(m);V.texImage2D(a,b,c,d,e,f,k,m,r,n>>Yc(r))}else V.texImage2D(a,b,c,d,e,
f,k,m,null);else V.texImage2D(a,b,c,d,e,f,k,m,n?Zc(m,k,d,e,n):null)},Vc:function(a,b,c,d,e,f,k,m,n,r){if(V.sf)V.texImage3D(a,b,c,d,e,f,k,m,n,r);else if(r){var t=Xc(n);V.texImage3D(a,b,c,d,e,f,k,m,n,t,r>>Yc(t))}else V.texImage3D(a,b,c,d,e,f,k,m,n,null)},Rd:function(a,b,c){V.texParameterf(a,b,c)},Qd:function(a,b,c){V.texParameterf(a,b,A[c>>2])},Pd:function(a,b,c){V.texParameteri(a,b,c)},Od:function(a,b,c){V.texParameteri(a,b,v[c>>2])},ab:function(a,b,c,d,e){V.texStorage2D(a,b,c,d,e)},$a:function(a,
b,c,d,e,f){V.texStorage3D(a,b,c,d,e,f)},Nd:function(a,b,c,d,e,f,k,m,n){if(2<=U.version)if(V.sf)V.texSubImage2D(a,b,c,d,e,f,k,m,n);else if(n){var r=Xc(m);V.texSubImage2D(a,b,c,d,e,f,k,m,r,n>>Yc(r))}else V.texSubImage2D(a,b,c,d,e,f,k,m,null);else r=null,n&&(r=Zc(m,k,e,f,n)),V.texSubImage2D(a,b,c,d,e,f,k,m,r)},Tc:function(a,b,c,d,e,f,k,m,n,r,t){if(V.sf)V.texSubImage3D(a,b,c,d,e,f,k,m,n,r,t);else if(t){var u=Xc(r);V.texSubImage3D(a,b,c,d,e,f,k,m,n,r,u,t>>Yc(u))}else V.texSubImage3D(a,b,c,d,e,f,k,m,n,
r,null)},mc:function(a,b,c,d){a=O[a];for(var e=[],f=0;f<b;f++)e.push(E(v[c+4*f>>2]));V.transformFeedbackVaryings(a,e,d)},Md:function(a,b){V.uniform1f(W(a),b)},Ld:function(a,b,c){if(2<=U.version)V.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=$c[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)}},Jd:function(a,b){V.uniform1i(W(a),b)},Id:function(a,b,c){if(2<=U.version)V.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=ad[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];
else d=v.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)}},bc:function(a,b){V.uniform1ui(W(a),b)},Zb:function(a,b,c){V.uniform1uiv(W(a),G,c>>2,b)},Hd:function(a,b,c){V.uniform2f(W(a),b,c)},Gd:function(a,b,c){if(2<=U.version)V.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=$c[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)}},Fd:function(a,b,c){V.uniform2i(W(a),b,c)},Ed:function(a,b,c){if(2<=U.version)V.uniform2iv(W(a),v,c>>2,2*
b);else{if(144>=b)for(var d=ad[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)}},ac:function(a,b,c){V.uniform2ui(W(a),b,c)},Yb:function(a,b,c){V.uniform2uiv(W(a),G,c>>2,2*b)},Dd:function(a,b,c,d){V.uniform3f(W(a),b,c,d)},Cd:function(a,b,c){if(2<=U.version)V.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=$c[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),
d)}},Bd:function(a,b,c,d){V.uniform3i(W(a),b,c,d)},Ad:function(a,b,c){if(2<=U.version)V.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b)for(var d=ad[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)}},$b:function(a,b,c,d){V.uniform3ui(W(a),b,c,d)},Xb:function(a,b,c){V.uniform3uiv(W(a),G,c>>2,3*b)},yd:function(a,b,c,d,e){V.uniform4f(W(a),b,c,d,e)},xd:function(a,b,c){if(2<=U.version)V.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=
b){var d=$c[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=A.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)}},wd:function(a,b,c,d,e){V.uniform4i(W(a),b,c,d,e)},vd:function(a,b,c){if(2<=U.version)V.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b)for(var d=ad[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)}},_b:function(a,b,c,d,
e){V.uniform4ui(W(a),b,c,d,e)},Wb:function(a,b,c){V.uniform4uiv(W(a),G,c>>2,4*b)},Kb:function(a,b,c){a=O[a];V.uniformBlockBinding(a,b,c)},ud:function(a,b,c,d){if(2<=U.version)V.uniformMatrix2fv(W(a),!!c,A,d>>2,4*b);else{if(72>=b)for(var e=$c[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);V.uniformMatrix2fv(W(a),!!c,e)}},Gc:function(a,b,c,d){V.uniformMatrix2x3fv(W(a),!!c,A,d>>2,6*b)},Ec:function(a,b,c,d){V.uniformMatrix2x4fv(W(a),
!!c,A,d>>2,8*b)},td:function(a,b,c,d){if(2<=U.version)V.uniformMatrix3fv(W(a),!!c,A,d>>2,9*b);else{if(32>=b)for(var e=$c[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);V.uniformMatrix3fv(W(a),!!c,e)}},Fc:function(a,b,c,d){V.uniformMatrix3x2fv(W(a),!!c,A,d>>2,6*b)},Cc:function(a,b,c,d){V.uniformMatrix3x4fv(W(a),
!!c,A,d>>2,12*b)},sd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=$c[16*b-1],f=A;d>>=2;for(var k=0;k<16*b;k+=16){var m=d+k;e[k]=f[m];e[k+1]=f[m+1];e[k+2]=f[m+2];e[k+3]=f[m+3];e[k+4]=f[m+4];e[k+5]=f[m+5];e[k+6]=f[m+6];e[k+7]=f[m+7];e[k+8]=f[m+8];e[k+9]=f[m+9];e[k+10]=f[m+10];e[k+11]=f[m+11];e[k+12]=f[m+12];e[k+13]=f[m+13];e[k+14]=f[m+14];e[k+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)}},Dc:function(a,b,c,d){V.uniformMatrix4x2fv(W(a),
!!c,A,d>>2,8*b)},Bc:function(a,b,c,d){V.uniformMatrix4x3fv(W(a),!!c,A,d>>2,12*b)},rd:function(a){a=O[a];V.useProgram(a);V.Ig=a},qd:function(a){V.validateProgram(O[a])},pd:function(a,b){V.vertexAttrib1f(a,b)},nd:function(a,b){V.vertexAttrib1f(a,A[b>>2])},md:function(a,b,c){V.vertexAttrib2f(a,b,c)},ld:function(a,b){V.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},kd:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},jd:function(a,b){V.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},id:function(a,b,c,d,e){V.vertexAttrib4f(a,
b,c,d,e)},hd:function(a,b){V.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},nb:function(a,b){V.vertexAttribDivisor(a,b)},ta:function(a,b){V.vertexAttribDivisor(a,b)},cd:function(a,b){V.vertexAttribDivisor(a,b)},ed:function(a,b){V.vertexAttribDivisor(a,b)},Za:function(a,b){V.vertexAttribDivisor(a,b)},hc:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},fc:function(a,b){V.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},gc:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},ec:function(a,
b){V.vertexAttribI4ui(a,G[b>>2],G[b+4>>2],G[b+8>>2],G[b+12>>2])},kc:function(a,b,c,d,e){V.vertexAttribIPointer(a,b,c,d,e)},gd:function(a,b,c,d,e,f){V.vertexAttribPointer(a,b,c,!!d,e,f)},fd:function(a,b,c,d){V.viewport(a,b,c,d)},Db:function(a,b,c,d){V.waitSync(Ec[a],b,(c>>>0)+4294967296*d)},e:function(){return 0},Ka:function(a,b,c){C.copyWithin(a,b,b+c)},h:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<
d%65536&&(d+=65536-d%65536);a:{try{xa.grow(Math.min(2147483648,d)-Ia.byteLength+65535>>>16);Ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},pa:function(a,b,c){a=H.get(a);Qd(a,b,c)},d:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Qa:function(a){for(var b=rc();rc()-b<a;);},Na:function(a,b){try{var c=0;Td().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);
q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof N&&d instanceof K||p(d),d.mf}},Oa:function(a,b){try{var c=Td();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});v[b>>2]=d;return 0}catch(e){return"undefined"!==typeof N&&e instanceof K||p(e),e.mf}},k:function(a){Rd(a)},i:function(a){try{var b=qc(a);Xb(b);return 0}catch(c){return"undefined"!==typeof N&&c instanceof K||p(c),c.mf}},Ma:function(a,b){try{var c=qc(a);q[b>>0]=c.tty?2:M(c.mode)?3:40960===(c.mode&61440)?7:
4;return 0}catch(d){return"undefined"!==typeof N&&d instanceof K||p(d),d.mf}},m:function(a,b,c,d){try{a:{for(var e=qc(a),f=a=0;f<c;f++){var k=v[b+(8*f+4)>>2],m=e,n=v[b+8*f>>2],r=k,t=void 0,u=q;if(0>r||0>t)throw new K(28);if(null===m.fd)throw new K(8);if(1===(m.flags&2097155))throw new K(8);if(M(m.node.mode))throw new K(31);if(!m.jf.read)throw new K(28);var w="undefined"!==typeof t;if(!w)t=m.position;else if(!m.seekable)throw new K(70);var y=m.jf.read(m,u,n,r,t);w||(m.position+=y);var B=y;if(0>B){var D=
-1;break a}a+=B;if(B<k)break}D=a}v[d>>2]=D;return 0}catch(I){return"undefined"!==typeof N&&I instanceof K||p(I),I.mf}},Ja:function(a,b,c,d,e){try{var f=qc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Yb(f,a,d);x=[f.position>>>0,(z=f.position,1<=+Math.abs(z)?0<z?(Math.min(+Math.floor(z/4294967296),4294967295)|0)>>>0:~~+Math.ceil((z-+(~~z>>>0))/4294967296)>>>0:0)];v[e>>2]=x[0];v[e+4>>2]=x[1];f.bg&&0===a&&0===d&&(f.bg=null);return 0}catch(k){return"undefined"!==typeof N&&
k instanceof K||p(k),k.mf}},Ta:function(a,b,c,d){try{a:{for(var e=qc(a),f=a=0;f<c;f++){var k=Zb(e,q,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}v[d>>2]=m;return 0}catch(n){return"undefined"!==typeof N&&n instanceof K||p(n),n.mf}},j:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},Ae:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;
else{d?Cd():Od(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Wd[139265];e==X.length&&(d?g.xf=yd(g.canvas,!0,!0,{antialias:1<Wd[135181],depth:0<Wd[135173],stencil:0<Wd[135174],alpha:0<Wd[135172]}):kc());!g.xf&&d?f=0:(a=new Vd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},Ve:function(){Wd=Zd},yc:function(a){a:{if(a=Xd(a)){a.Bg&&H.get(a.Bg)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.xf=void 0}a=void 0}return a},Uc:function(a,b,
c){ua(b,Id,"double");ua(c,Jd,"double")},Jc:function(a,b,c){var d=0,e=0;if(a=Xd(a))d=a.width,e=a.height;b&&ua(b,d,"i32");c&&ua(c,e,"i32")},z:function(){if(X)return 1;rc();Wd=Zd;X=[];Y=null;window.addEventListener("gamepadconnected",de,!0);window.addEventListener("gamepaddisconnected",fe,!0);window.addEventListener("keydown",ge,!0);window.addEventListener("keypress",be,!0);window.addEventListener("keyup",he,!0);window.addEventListener("blur",ie,!0);g.canvas.addEventListener("touchmove",je,!0);g.canvas.addEventListener("touchstart",
ne,!0);g.canvas.addEventListener("touchcancel",pe,!0);g.canvas.addEventListener("touchend",pe,!0);g.canvas.addEventListener("mousemove",je,!0);g.canvas.addEventListener("mousedown",ne,!0);g.canvas.addEventListener("mouseup",pe,!0);g.canvas.addEventListener("wheel",qe,!0);g.canvas.addEventListener("mousewheel",qe,!0);g.canvas.addEventListener("mouseenter",ke,!0);g.canvas.addEventListener("mouseleave",le,!0);g.canvas.addEventListener("drop",ve,!0);g.canvas.addEventListener("dragover",we,!0);Nd.push(function(a,
b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.yg=Y.x,Y.zg=Y.y,Y.xg=Y.width,Y.wg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.ag=!0):1==Y.ag?(Y.x=Y.yg,Y.y=Y.zg,Y.width=Y.xg,Y.height=Y.wg,Y.ag=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Od(Y.width,Y.height,!0),Y&&Y.Dg&&H.get(Y.Dg)(Y.id,Y.width,Y.height),Y&&Y.If&&H.get(Y.If)(Y.id,Y.width,Y.height))}});return 1},pe:function(){},ea:function(){},Vd:function(a,
b){if(a=Xd(a)){var c=a.Gf;a.Gf=b;b=c}else b=null;return b},K:function(a){var b=Yd;Yd=a;return b},ee:function(a,b){a=Xd(a);if(!a)return null;var c=a.If;a.If=b;return c},Kd:function(a,b){if(a=Xd(a)){var c=a.Jf;a.Jf=b;b=c}else b=null;return b},od:function(a,b){if(a=Xd(a)){var c=a.Qf;a.Qf=b;b=c}else b=null;return b},zd:function(a,b){if(a=Xd(a)){var c=a.Sf;a.Sf=b;b=c}else b=null;return b},dd:function(a,b){a=Xd(a);if(!a)return null;var c=a.Cg;a.Cg=b;return c},V:function(){},nc:function(){window.removeEventListener("gamepadconnected",
de,!0);window.removeEventListener("gamepaddisconnected",fe,!0);window.removeEventListener("keydown",ge,!0);window.removeEventListener("keypress",be,!0);window.removeEventListener("keyup",he,!0);window.removeEventListener("blur",ie,!0);g.canvas.removeEventListener("touchmove",je,!0);g.canvas.removeEventListener("touchstart",ne,!0);g.canvas.removeEventListener("touchcancel",pe,!0);g.canvas.removeEventListener("touchend",pe,!0);g.canvas.removeEventListener("mousemove",je,!0);g.canvas.removeEventListener("mousedown",
ne,!0);g.canvas.removeEventListener("mouseup",pe,!0);g.canvas.removeEventListener("wheel",qe,!0);g.canvas.removeEventListener("mousewheel",qe,!0);g.canvas.removeEventListener("mouseenter",ke,!0);g.canvas.removeEventListener("mouseleave",le,!0);g.canvas.removeEventListener("drop",ve,!0);g.canvas.removeEventListener("dragover",we,!0);g.canvas.width=g.canvas.height=1;Y=X=null},f:function(a,b){Wd[a]=b},Aa:function(){v[ze()>>2]=52;return-1},l:function(){},c:function(){return 0}};
(function(){function a(e){g.asm=e.exports;xa=g.asm.We;Ka();H=g.asm.df;Ma.unshift(g.asm.Xe);Ua("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ce};Ta("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||"function"!==
typeof WebAssembly.instantiateStreaming||Va()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Xe).apply(null,arguments)};
var ue=g._free=function(){return(ue=g._free=g.asm.Ye).apply(null,arguments)},Ba=g._malloc=function(){return(Ba=g._malloc=g.asm.Ze).apply(null,arguments)},ze=g.___errno_location=function(){return(ze=g.___errno_location=g.asm._e).apply(null,arguments)};g._main=function(){return(g._main=g.asm.$e).apply(null,arguments)};
var Be=g._memset=function(){return(Be=g._memset=g.asm.af).apply(null,arguments)},Ha=g.stackAlloc=function(){return(Ha=g.stackAlloc=g.asm.bf).apply(null,arguments)},Ae=g._memalign=function(){return(Ae=g._memalign=g.asm.cf).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.ef).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.ff).apply(null,arguments)};g.addRunDependency=Ta;g.removeRunDependency=Ua;g.FS_createPath=cc;g.FS_createDataFile=ec;
g.FS_createPreloadedFile=jc;g.FS_createLazyFile=ic;g.FS_createDevice=fc;g.FS_unlink=Tb;var De;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function Ee(){De||Fe();De||(Sa=Ee)};
function Fe(a){function b(){if(!De&&(De=!0,g.calledRun=!0,!ya)){g.noFSInit||ac||(ac=!0,$b(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?fc("/dev","stdin",g.stdin):Sb("/dev/tty","/dev/stdin"),g.stdout?fc("/dev","stdout",null,g.stdout):Sb("/dev/tty","/dev/stdout"),g.stderr?fc("/dev","stderr",null,g.stderr):Sb("/dev/tty1","/dev/stderr"),Vb("/dev/stdin",0),Vb("/dev/stdout",1),Vb("/dev/stderr",1));cb(Ma);Ab=!1;cb(Na);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ge){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Ha(4*(e+1));v[f>>2]=Ga(da);for(var k=1;k<e;k++)v[(f>>2)+k]=Ga(c[k-1]);v[(f>>2)+e]=0;try{var m=d(e,f);Rd(m,!0)}catch(n){n instanceof pa||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),h("exception thrown: "+c),ea(1,n))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Oa.unshift(c);cb(Oa)}}a=a||ca;if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Pa();
cb(La);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Fe;function Rd(a,b){za=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ya=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ge=!0;g.noInitialRun&&(Ge=!1);Fe();
